import { useEffect, useState } from 'react';
import { FiCheckCircle, FiAlertCircle, FiArrowRight, FiCpu, FiSliders } from 'react-icons/fi';
import Modal from './Modal';
import { aiApi } from '../api';
import { getErrorMessage } from '../api/client';
import { Skeleton, Alert } from './ui';

/** Circular 0-100 fit score, colour-coded on the same scale the backend calibrates to. */
function ScoreRing({ score }) {
  const value = Math.max(0, Math.min(100, Math.round(score ?? 0)));
  const color = value >= 70 ? 'text-emerald-500' : value >= 40 ? 'text-amber-500' : 'text-slate-400';
  return (
    <div className="relative flex h-16 w-16 shrink-0 items-center justify-center">
      <svg className="h-16 w-16 -rotate-90" viewBox="0 0 36 36">
        <circle cx="18" cy="18" r="16" fill="none" className="stroke-slate-100 dark:stroke-slate-700" strokeWidth="3" />
        <circle
          cx="18" cy="18" r="16" fill="none"
          className={`${color} stroke-current`}
          strokeWidth="3"
          strokeDasharray={`${(value / 100) * 100.53} 100.53`}
          strokeLinecap="round"
        />
      </svg>
      <span className={`absolute text-sm font-bold ${color}`}>{value}%</span>
    </div>
  );
}

/**
 * Tells the user which engine produced the feedback. The API always reports this, so we never
 * present heuristic output as if a model wrote it.
 */
function SourceBadge({ source }) {
  const isModel = source === 'claude';
  const Icon = isModel ? FiCpu : FiSliders;
  return (
    <span
      title={isModel
        ? 'Generated by Claude from your profile and the job description'
        : 'Generated by the built-in rule-based engine (no AI provider configured)'}
      className={`badge inline-flex items-center gap-1 ${
        isModel
          ? 'bg-brand-50 text-brand-700 dark:bg-brand-900/30 dark:text-brand-300'
          : 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300'
      }`}
    >
      <Icon className="h-3 w-3" /> {isModel ? 'Claude' : 'Rule-based'}
    </span>
  );
}

function PointList({ title, items, icon: Icon, tone }) {
  if (!items?.length) return null;
  const tones = {
    emerald: 'text-emerald-500',
    amber: 'text-amber-500',
    brand: 'text-brand-500',
  };
  return (
    <div>
      <div className="mb-1.5 text-sm font-medium text-slate-700 dark:text-slate-200">{title}</div>
      <ul className="space-y-1.5 text-sm text-slate-600 dark:text-slate-300">
        {items.map((text, i) => (
          <li key={i} className="flex items-start gap-2">
            <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${tones[tone]}`} />
            <span>{text}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

/**
 * Fetches and displays AI feedback for one of the candidate's applications.
 * Pass `applicationId` to open; `null` closes it.
 */
export default function AiFeedbackModal({ applicationId, onClose }) {
  const [feedback, setFeedback] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!applicationId) return;

    let cancelled = false;
    setFeedback(null);
    setError(null);

    aiApi.applicationFeedback(applicationId)
      .then((data) => { if (!cancelled) setFeedback(data); })
      .catch((e) => { if (!cancelled) setError(getErrorMessage(e)); });

    // The request can outlive the modal — ignore a late response rather than setting state on a
    // closed dialog.
    return () => { cancelled = true; };
  }, [applicationId]);

  return (
    <Modal open={!!applicationId} onClose={onClose} title="AI Application Feedback">
      {error ? (
        <Alert type="error" title="Couldn't generate feedback">{error}</Alert>
      ) : !feedback ? (
        <div className="space-y-3">
          <Skeleton className="h-16 w-full" />
          <Skeleton className="h-4 w-3/4" />
          <Skeleton className="h-24 w-full" />
          <p className="text-center text-xs text-slate-400">Analysing your profile against this role…</p>
        </div>
      ) : (
        <div className="space-y-5">
          <div className="flex items-start gap-4">
            <ScoreRing score={feedback.matchScore} />
            <div className="min-w-0">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-semibold text-slate-900 dark:text-white">{feedback.jobTitle}</span>
                <SourceBadge source={feedback.source} />
              </div>
              <p className="text-sm text-slate-500 dark:text-slate-400">{feedback.organizationName}</p>
            </div>
          </div>

          <p className="rounded-lg bg-slate-50 p-3 text-sm leading-relaxed text-slate-700 dark:bg-slate-800/60 dark:text-slate-200">
            {feedback.summary}
          </p>

          <PointList title="What's working for you" items={feedback.strengths} icon={FiCheckCircle} tone="emerald" />
          <PointList title="Gaps for this role" items={feedback.gaps} icon={FiAlertCircle} tone="amber" />
          <PointList title="Suggested next steps" items={feedback.recommendations} icon={FiArrowRight} tone="brand" />

          <p className="border-t border-slate-100 pt-3 text-xs text-slate-400 dark:border-slate-700">
            Automated guidance based on your profile and this job description. It is not a hiring
            decision and does not reflect the recruiter's view of your application.
          </p>
        </div>
      )}
    </Modal>
  );
}
