import { useCallback, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FiCalendar, FiVideo, FiMapPin, FiPhone, FiExternalLink, FiInfo, FiX } from 'react-icons/fi';
import { interviewsApi } from '../../api';
import { getErrorMessage } from '../../api/client';
import { useToast } from '../../contexts/ToastContext';
import { PageHeader, EmptyState, Skeleton, StatusBadge } from '../../components/ui';

const MODE_ICON = { Video: FiVideo, Onsite: FiMapPin, Phone: FiPhone };

/** A candidate's scheduled interviews, with calendar links generated by the backend. */
export default function UpcomingInterviews() {
  const { toast } = useToast();
  const [items, setItems] = useState(null);
  const [expandedId, setExpandedId] = useState(null);

  const load = useCallback(() => {
    interviewsApi.list({ upcomingOnly: true })
      .then(setItems)
      .catch((e) => { toast(getErrorMessage(e), 'error'); setItems([]); });
  }, [toast]);

  useEffect(() => { load(); }, [load]);

  return (
    <div>
      <PageHeader
        icon={FiCalendar}
        title="Upcoming Interviews"
        subtitle="Add them to your calendar so you don't miss a thing"
      />

      {items === null ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-24 w-full" />)}
        </div>
      ) : items.length ? (
        <div className="space-y-3">
          {items.map((iv, idx) => {
            const Icon = MODE_ICON[iv.mode] || FiCalendar;
            const when = new Date(iv.interviewDate);
            const isOpen = expandedId === iv.interviewId;

            return (
              <motion.div
                key={iv.interviewId}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="card p-4"
              >
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div className="flex items-start gap-4">
                    <div className="flex h-12 w-12 flex-col items-center justify-center rounded-xl bg-gradient-to-br from-brand-500 to-accent-500 text-white">
                      <span className="text-xs font-medium uppercase">
                        {when.toLocaleString(undefined, { month: 'short' })}
                      </span>
                      <span className="text-lg font-bold leading-none">{when.getDate()}</span>
                    </div>
                    <div>
                      <div className="font-medium text-slate-800 dark:text-slate-100">{iv.jobTitle}</div>
                      <div className="text-sm text-slate-500">{iv.companyName}</div>
                      <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-400">
                        <Icon className="h-3.5 w-3.5" />
                        {iv.mode}
                        {' · '}
                        {/* Rendered in the viewer's own time zone, not UTC. */}
                        {when.toLocaleString(undefined, {
                          weekday: 'short', hour: '2-digit', minute: '2-digit',
                        })}
                        {' · '}{iv.durationMinutes} min
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-wrap items-center gap-2">
                    <StatusBadge status={iv.status} />
                    {iv.meetingLink && (
                      <a href={iv.meetingLink} target="_blank" rel="noopener noreferrer" className="btn-primary">
                        <FiVideo /> Join Meeting
                      </a>
                    )}
                    <button
                      className="btn-secondary"
                      onClick={() => setExpandedId(isOpen ? null : iv.interviewId)}
                      aria-expanded={isOpen}
                    >
                      {isOpen ? <FiX /> : <FiInfo />} {isOpen ? 'Hide' : 'View Details'}
                    </button>
                  </div>
                </div>

                {isOpen && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="mt-4 border-t border-slate-200 pt-4 dark:border-slate-700"
                  >
                    <dl className="grid gap-3 text-sm sm:grid-cols-2">
                      <div>
                        <dt className="text-slate-500">Title</dt>
                        <dd className="font-medium text-slate-800 dark:text-slate-100">{iv.title}</dd>
                      </div>
                      <div>
                        <dt className="text-slate-500">Ends</dt>
                        <dd className="font-medium text-slate-800 dark:text-slate-100">
                          {new Date(iv.endsAt).toLocaleString(undefined, { hour: '2-digit', minute: '2-digit' })}
                        </dd>
                      </div>
                      {iv.location && (
                        <div>
                          <dt className="text-slate-500">Location</dt>
                          <dd className="font-medium text-slate-800 dark:text-slate-100">{iv.location}</dd>
                        </div>
                      )}
                      {iv.notes && (
                        <div className="sm:col-span-2">
                          <dt className="text-slate-500">Notes</dt>
                          <dd className="text-slate-700 dark:text-slate-200">{iv.notes}</dd>
                        </div>
                      )}
                    </dl>

                    <div className="mt-4 flex flex-wrap gap-2">
                      {/* Link comes from the API — never constructed in the browser. */}
                      <a href={iv.googleCalendarUrl} target="_blank" rel="noopener noreferrer" className="btn-secondary">
                        <FiExternalLink /> Add to Google Calendar
                      </a>
                    </div>
                  </motion.div>
                )}
              </motion.div>
            );
          })}
        </div>
      ) : (
        <EmptyState
          icon={FiCalendar}
          title="No upcoming interviews"
          message="When a recruiter schedules an interview, it will appear here and you'll get an email invitation."
        />
      )}
    </div>
  );
}
